fix worldgenjson't caves
hYdos/Lint pull request #100
Opened 2021-10-14 19:42 UTC by sylv256

## Changelog
 - Fix cavegen

## Todo
 - [x] #87 
 - [x] Tested

2021-10-14 22:12 UTC, ramidzkh requested changes
Could you also fix that once place in structures where it's using the legacy method and putting structure void everywhere?

2021-10-14 22:12 UTC, ramidzkh commented on src/main/java/me/hydos/lint/world/carver/LintCaveCarver.java
> +		return state.isOf(LintBlocks.FUSED_STONE) || state.isOf(LintBlocks.INDIGO_STONE) || state.isOf(LintBlocks.CORRUPT_GRASS) || state.isOf(LintBlocks.LIVELY_GRASS) || state.isOf(LintBlocks.FROSTED_GRAS
Make a tag at this point

2021-10-14 22:12 UTC, ramidzkh commented on src/main/java/me/hydos/lint/world/carver/LintCaveCarver.java
> +		if (blockState.isOf(LintBlocks.CORRUPT_GRASS) || blockState.isOf(LintBlocks.LIVELY_GRASS) || blockState.isOf(LintBlocks.FROSTED_GRASS)) {
Tag here too

2021-10-14 23:24 UTC, valoeghese requested changes

2021-10-14 23:24 UTC, valoeghese commented on src/main/java/me/hydos/lint/world/carver/LintCaveCarver.java
> +		return state.isOf(LintBlocks.FUSED_STONE) || state.isOf(LintBlocks.INDIGO_STONE) || state.isOf(LintBlocks.CORRUPT_GRASS) || state.isOf(LintBlocks.LIVELY_GRASS) || state.isOf(LintBlocks.FROSTED_GRAS
Firstly, this doesn't match vanilla behaviour. This is what needs to be done:
- For the sand/gravel like blocks, you need `&& !stateAbove.getFluidState().isIn(FluidTags.WATER)`
- Secondly, don't carve Asphalt or Ash. Dawn shardlands doesn't need caves. It's a hecking floating island it's thin enough.
-  You can remove Super.canCarveBlock at this point because we don't use vanilla blocks.
- Finally, remove the grass from this method. Vanilla doesn't touch grass here.

2021-10-14 23:24 UTC, valoeghese commented on src/main/java/me/hydos/lint/world/carver/LintCaveCarver.java
> +		if (blockState.isOf(LintBlocks.CORRUPT_GRASS) || blockState.isOf(LintBlocks.LIVELY_GRASS) || blockState.isOf(LintBlocks.FROSTED_GRASS)) {
Alternatively `use DirtLikeBlock.isLintGrass()`

2021-10-14 23:24 UTC, valoeghese commented on src/main/java/me/hydos/lint/world/carver/LintConfiguredCarvers.java
> +	ConfiguredCarver<LintCaveCarverConfig> CAVE = Registry.register(BuiltinRegistries.CONFIGURED_CARVER, Lint.id("nebulaes_bane"), LintCaveCarver.CAVE.configure(new LintCaveCarverConfig(BiasedToBottomHe
what are all these new parameters

2021-10-15 23:43 UTC, TehcJS commented
i'll finish doing this once i'm like halfway done with #103

2021-10-16 23:08 UTC, sylv256 commented on src/main/java/me/hydos/lint/world/carver/LintConfiguredCarvers.java
> +	ConfiguredCarver<LintCaveCarverConfig> CAVE = Registry.register(BuiltinRegistries.CONFIGURED_CARVER, Lint.id("nebulaes_bane"), LintCaveCarver.CAVE.configure(new LintCaveCarverConfig(BiasedToBottomHe
This is the new 1.17 cavegen

2021-10-16 23:10 UTC, sylv256 commented on src/main/java/me/hydos/lint/world/carver/LintCaveCarver.java
> +		return state.isOf(LintBlocks.FUSED_STONE) || state.isOf(LintBlocks.INDIGO_STONE) || state.isOf(LintBlocks.CORRUPT_GRASS) || state.isOf(LintBlocks.LIVELY_GRASS) || state.isOf(LintBlocks.FROSTED_GRAS
If I remove the grass from this method, caves don't break the surface.

2021-10-17 06:09 UTC, valoeghese commented on src/main/java/me/hydos/lint/world/carver/LintCaveCarver.java
> +		return state.isOf(LintBlocks.FUSED_STONE) || state.isOf(LintBlocks.INDIGO_STONE) || state.isOf(LintBlocks.CORRUPT_GRASS) || state.isOf(LintBlocks.LIVELY_GRASS) || state.isOf(LintBlocks.FROSTED_GRAS
Okay so grass is allowed it seems. I fixed 1,2,3 of my points so this is fine

2021-10-17 06:10 UTC, sylv256 commented
i already ahve the changes locally i forgot to push lol

2021-10-17 06:14 UTC, valoeghese approved these changes

2021-10-17 06:15 UTC, valoeghese commented
> i already ahve the changes locally i forgot to push lol

He Forgor 💀

2021-10-17 06:16 UTC, valoeghese commented
Can you merge with my changes then and push? Getting this merged would be nice

2021-10-17 06:17 UTC, TehcJS commented
i'm trying out custom tags
also i have tons of refactors

2021-10-17 06:22 UTC, TehcJS commented
![2021-10-17_02 22 29](https://user-images.githubusercontent.com/18603248/137614314-d05ba989-b98b-48a5-a2fe-563076468da3.png)
fixed (with block tags, of course!)

2021-10-17 06:30 UTC, sylv256 commented
should i merge now?

2021-10-17 06:31 UTC, TehcJS commented
I put the grass and stone in `grass.json` and `stone.json` respectively. i'm using tags like @ramidzkh suggested.

2021-10-17 06:38 UTC, sylv256 commented on src/main/resources/data/lint/tags/blocks/dirt.json
> +  "require": false,
this should be "replace"

2021-10-17 06:43 UTC, TehcJS commented
:crab:

2021-10-17 06:44 UTC, merged

2021-10-17 06:46 UTC, valoeghese requested changes
Only a few problems

2021-10-17 06:46 UTC, valoeghese commented on src/main/java/me/hydos/lint/world/carver/LintCaveCarver.java
> +		return (state.isIn(LintBlockTags.STONE) || state.isIn(LintBlockTags.DIRT) || state.isIn(LintBlockTags.GRASS)) && !stateAbove.getFluidState().isIn(FluidTags.WATER);
THis check is slightly wrong. The underwater check is for underwater type (sand/gravel) blocks.

2021-10-17 06:46 UTC, valoeghese commented on src/main/java/me/hydos/lint/world/feature/CanopyTreeFeature.java
> +					float r = 4 - 0.5f * dymod * (1 + 0.1f * dymod * dymod); // radius
oh lmao I didn't even see the redundant check

2021-10-17 06:46 UTC, valoeghese commented on src/main/java/me/hydos/lint/world/layer/GenericBiomes.java
> +public record GenericBiomes(Registry<Biome> biomeRegistry,
what the fuck those were private without getters

2021-10-17 06:54 UTC, sylv256 commented on src/main/java/me/hydos/lint/world/carver/LintCaveCarver.java
> +		return (state.isIn(LintBlockTags.STONE) || state.isIn(LintBlockTags.DIRT) || state.isIn(LintBlockTags.GRASS)) && !stateAbove.getFluidState().isIn(FluidTags.WATER);
I don't need to make sure caves don't spawn underwater?

2021-10-17 06:55 UTC, sylv256 commented on src/main/java/me/hydos/lint/world/layer/GenericBiomes.java
> +public record GenericBiomes(Registry<Biome> biomeRegistry,
intellijank warned me to change it to a record